# this is a custom configuration not affiliated with CFSSL

cfssl:
  domain: paxarm.com
  C: US
  ST: California  
  L: San Francisco
  O: Paxarm
  OU: Paxarm
  validity: 876000h  # 100 years

openvpn:
  remote: s.paxarm.com
  port: 1194
  dev: tun
